db:
    database: app-db
    user: app-user
    host: 127.0.0.1
    port: 5432
web:
    host: 127.0.0.1
    port: 8000
vault:
    host: 127.0.0.1
    port: 8200
    auth_token: s.5mWEl6cmSGIwBlWEa1jqmCKn
    role_id: f89be9a6-3f7f-18bf-73a8-44b165c3eb61
